{{- if .Values.postgresql.secret.initUserDbSql -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: 
  name: secret-postgres-init-db-user
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  01-init-user-db.sql: {{ .Values.postgresql.secret.initUserDbSql }}
{{- end -}}
